### ISSUE TITLE
Fill percertage value

### ISSUE THREAD

**Issue by leopeng1995** [pshihn/rough#101]
![image](https://user-images.githubusercontent.com/10773297/54083962-aaee1b80-4365-11e9-9954-592d2c5121b1.png)

How can I do this?

**Comment by ishidex2** [comment]
This is not really a purpose of rough.js, rough.js provides you hand-drawn-like graphics, this is not a case, you should think yourself how to implement it, for this you have rough.js paths

**Comment by omarsedki** [comment]
@leopeng1995 you can make with this free  online tool https://livegap.com/iconmatrix
