### ISSUE TITLE
fails on 90 degree lines

### ISSUE THREAD

**Issue by cpryland** [pshihn/rough#105]
Rough appears to fail (does something degenerate) on simple line segments (whether actual lines, or simple line paths) with 90 degree orientation (where the start.x == end.x or start.y == end.y).

Is this something you've seen before?

**Comment by pshihn** [comment]
I recall seeing this before. Didn't realize it was still an issue. Will look into this. Thanks for reporting.

**Comment by cpryland** [comment]
Any ideas?

**Comment by pshihn** [comment]
Resolved in https://github.com/pshihn/rough/pull/121 which uses a new hachure algoritjm
