### ISSUE TITLE
should really scale roughness for size

### ISSUE THREAD

**Issue by cpryland** [pshihn/rough#106]
Right now, roughness isn't scaled for size, so if you roughen a very small object (say 8px) a given mid-range roughness would be wildly rough, but the same would be almost invisible on a large (512px) object.

Seems like it should auto-scale roughness for the max(height, width) of the bounding box for the object being roughened.

**Comment by pshihn** [comment]
That's a good idea. It's tricky to think about what the library should have vs what the application needs. As the user of rough.js you can set the roughness to whatever your needs maybe to that size. I am hesitant to give a global solution that may not work for others.

**Comment by cpryland** [comment]
Yes, but figuring out how to scale the roughness per size is tough. Some kind of log scale is clearly indicated, to make a 4px figure the same visual roughness as a 4000px figure. Been playing with scaling and it's quite messy.

Also, what to scale to? Longest dimension?

And scaling seems to affect ellipse "fill" a lot more than rectangle fill, etc.

**Comment by pshihn** [comment]
Resolved in https://github.com/pshihn/rough/pull/121
