### ISSUE TITLE
Please document the NPM usage

### ISSUE THREAD

**Issue by Tumulte** [pshihn/rough#107]
hi,

If I do rough = require('roughjs') it says that "rough.svg()" is not a function.

I've tried import without any more luck

Thanks for your help

**Comment by pshihn** [comment]
I think it depends on your environment. 
Usually in es6 you can just do 

`import rough from "roughjs"`

or 

`import rough from "roughjs/bin/wrappers/rough"`

**Comment by pshihn** [comment]
added to readme

**Comment by hiddenwaffle** [comment]
For anyone googling, neither worked for me, but this one did:
`import rough from 'roughjs/bin/rough'`
