### ISSUE TITLE
Is it possible to show a drawing animation?

### ISSUE THREAD

**Issue by ProgrammingLife** [pshihn/rough#108]
I wanna create an animation that would draw my SVG step by step using rough. I don't know where to start. Please help me :)

**Comment by pshihn** [comment]
Yes people have created animations using rough. You would have to add your own animation logic though. If you're using SVG, then rough gives you the svg node and it's up to you when you append it to your image

**Comment by ProgrammingLife** [comment]
Sorry but I don't understand how to use generators in my case. I don't know how not to regenerate my line everytime:

```
function randomInteger(min, max) {
	let rand = min + Math.random() * (max + 1 - min);
	return Math.floor(rand);
}

const context = canvas.getContext('2d');
const rc = rough.canvas(document.getElementById('canvas'));
let points = [];
let lastX = 200;
let lastY = 200;
setInterval(() => {
	context.clearRect(0, 0, canvas.width, canvas.height);
	let shape = rc.linearPath(points, { roughness: 1.2, stroke: 'red', strokeWidth: 2 });
	let dX = randomInteger(-10, 10); let dY = randomInteger(-10, 10);
	let x = lastX + dX; let y = lastY + dY;
	points.push([x, y]);
	rc.draw(shape);
	lastX = x;	lastY = y;
}, 200);
```
I wanna add new point to existing shape and not to regenerate it again and again each cycle. How to achieve this?

**Comment by ProgrammingLife** [comment]
I'm trying to make some sort of a drawing by hand app. I can try to store each tiny line to array and then just do:
`for (let i = 0; i < lines.length; i++) rc.draw(lines[i]);`
but I think it's not the best solution because of large amount of such lines

**Comment by ProgrammingLife** [comment]
Thanks, I got it. It woks awesome!

**Comment by NiloCK** [comment]
@pshihn, @ProgrammingLife  Do you have any links to working animations?

**Comment by matthewturk** [comment]
I stumbled across this issue -- I made a really simple and hacky version of path drawing with roughjs:

https://observablehq.com/@matthewturk/path-interpolation-roughjs

Hopefully it's helpful.
