### ISSUE TITLE
Need a proper logo

### ISSUE THREAD

**Issue by pshihn** [pshihn/rough#112]
- Preferably generated using rough.js
- Give a sketchy feel
- If the logo is not square, must have a square equivalent

**Comment by EddyVinck** [comment]
Cool project! I'm about to go to bed, but I can take a look tomorrow after work! Are you looking for a logo with text or something else?

**Comment by pshihn** [comment]
Probably without text, but I am open. 
Ideally something indicating shapes
See  https://roughjs.com/ for some inspiration perhaps

**Comment by EddyVinck** [comment]
Alright! Do you just want the output or do you want the logo to be generated in the source code somehow?

**Comment by pshihn** [comment]
Not in the main source code.
A separate script file/html that generates it would be ideal.

**Comment by EddyVinck** [comment]
What do you think about something like this?

I tried to give it a sketchy whiteboard feel and I think it worked out by sticking to a couple colors and using different stroke widths. I used a few simple shapes like you suggested.

 I also learned how to write a triangle shape by hand, so there's that.

![image](https://user-images.githubusercontent.com/23434753/66506212-33d05f80-eacd-11e9-9f54-87b23672e499.png)

**Comment by pshihn** [comment]
I like the first one. It Kinda made me think of the letter 'R' for Rough.
Perhaps a version of the first one  which look kinda more like R but not really R? if that makes sense!

As for the colors, and the fill styles, being a script - it can be dynamic.

**Comment by blindingstars** [comment]
I have a (pardon the pun) rough idea of how the shapes could suggest an R:

<img src="https://user-images.githubusercontent.com/6765732/66707213-91012680-ed02-11e9-9e53-36d518f66ea1.png" width="250" />

...though the sketchiness is all faked in Illustrator. The unsketched, basic-shape SVG source is here if someone would like to mess around with it:

```
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">
  <polygon points="365.63 512.08 74 272 512 371 365.63 512" />
  <rect width="163" height="512" />
  <circle cx="264" cy="173" r="173" />
</svg>
```

**Comment by EddyVinck** [comment]
Thanks for the suggestion! I have some time today so I'll let you guys know when it's done.
