### ISSUE TITLE
Node support

### ISSUE THREAD

**Issue by chapuzzo** [pshihn/rough#115]
Is this library supposed to work with `node`?

I've been developing an image-morph application with it https://chapuzzo.github.io/randomart/

It works great in the browser but when I try to recreate the steps in backend for async generation or batches the fill doesn't cover the paths in whole. I use `svg`. 

I have tried using `canvas` instead and it doesn't work (I think it's because of getBBox). 

Is there any hack/workaround you already know for it to work?

<img height=270 src="https://user-images.githubusercontent.com/1598156/67195732-c7712c80-f3f9-11e9-84fe-1b99ef62e07c.jpg"><img height=270 src="https://user-images.githubusercontent.com/1598156/67196398-094ea280-f3fb-11e9-9dd2-7bcb2559762c.png"><img height=270 src="https://user-images.githubusercontent.com/1598156/67195651-9b55ab80-f3f9-11e9-8ecf-7a26c442ecfe.jpg">

images are `original` `browser` and `node` respectively

Thanks

**Comment by pshihn** [comment]
It should. Look at https://github.com/ismay/coarse which does exactly this

**Comment by pshihn** [comment]
Should all work with JSDOM . Not sure if https://github.com/ismay/coarse uses it but it does node level svg processing using roughjs
