### ISSUE TITLE
roughjs with react and typescript

### ISSUE THREAD

**Issue by joost2076** [pshihn/rough#116]
I am trying to use roughjs with react and typescript. 

I first encountered the webpack issue which is described here https://github.com/pshihn/rough/issues/99 and which can be solved by using ` import rough from 'roughjs/dist/rough.umd';`

There is now a new error popping up:
```
Could not find a declaration file for module 'roughjs/dist/rough.umd'. '/home/joost/Desktop/guitar/guitar/node_modules/roughjs/dist/rough.umd.js' implicitly has an 'any' type.
  Try `npm install @types/roughjs` if it exists or add a new declaration (.d.ts) file containing `declare module 'roughjs/dist/rough.umd';`  TS7016

```

**Comment by joost2076** [comment]
Solved, though not in the nicest way, by using require.
const rough = require('../node_modules/roughjs/dist/rough.umd');

https://stackoverflow.com/questions/41292559/could-not-find-a-declaration-file-for-module-module-name-path-to-module-nam

**Comment by kostasx** [comment]
Here's my solution:

```import rough from 'roughjs/bundled/rough.esm';```

**Comment by pshihn** [comment]
the bundle's module file is set to the es6 version. I think it depends on your bundler/compiler that expects the input files to be all bundled.
