### ISSUE TITLE
Add a new example to Wiki

### ISSUE THREAD

**Issue by kumilingus** [pshihn/rough#117]
Hi, congratulation on this awesome library! Would you mind adding a link to an interactive diagram demo amongst your wiki page examples? Thanks!

* demo: https://resources.jointjs.com/demos/rough

* markdown:
```| Interactive hand-drawn-like diagrams using [JointJS](https://github.com/clientIO/joint) and RoughJS | [View](https://resources.jointjs.com/demos/rough) |```

**Comment by with-shrey** [comment]
@pshihn Can i take this up ?

**Comment by pshihn** [comment]
@with-shrey go for it

**Comment by with-shrey** [comment]
@pshihn Thank You

**Comment by ProgrammingLife** [comment]
Nice one. Thanks for sharing!

**Comment by pshihn** [comment]
Done.
