### ISSUE TITLE
SVG path fill-hature instead of fill-pattern. 

### ISSUE THREAD

**Issue by wolfiex** [pshihn/rough#118]
Is it possible to output an individual path to represent the hature pattern, as opposed to the pattern fill that currently exists.  The current form causes problems for SVG parsing and plotting software.

**Comment by pshihn** [comment]
Yes i am planning to add that in a future release. It was a bit complicated and I went for an easy way out :/

**Comment by pshihn** [comment]
v4.2.0 does not have any pattern fills anymore, and paths are privided. 
This should solve this.
