### ISSUE TITLE
Examples are down

### ISSUE THREAD

**Issue by deepxg** [pshihn/rough#127]
All the example links to roughjs.com are 404s, and the previews also appear to be broken. No biggie, but would love to see them!

**Comment by brandly** [comment]
[they've been gone a whole year?](https://github.com/pshihn/rough/commit/560f4cb460f71394689de0740cab95908490d774)

**Comment by pshihn** [comment]
Ha! not for a whole year. That change was when I moved the site/examples to a separate repo. 
They broke with the v4.0 release. :(
Will fix shortly.

**Comment by brandly** [comment]
Ha my bad. I was confused by what I was seeing, since this repo looks so actively maintained

**Comment by ernestgn** [comment]
When will the examples be back? There are now no public reference implementations, let alone for v4.0 release, for any previous releases :-( 

@pshihn looked around your other repos to see where new examples could be, no dice.

**Comment by ernestgn** [comment]
I'm particularly interested in the US map example, which isn't available via roughViz

**Comment by pshihn** [comment]
Examples page has been fixed

There's a new Gallery page coming on the website as well
