### ISSUE TITLE
Fill lines stop when crossing 0

### ISSUE THREAD

**Issue by vjeux** [pshihn/rough#13]
This seems to happen both horizontally and vertically and doesn't look really good. Would be nice if it was one whole pattern: https://jsfiddle.net/g7o74vwr/

![image](https://user-images.githubusercontent.com/197597/37318259-c368ff16-2626-11e8-8940-cbe7cfe5cc69.png)

By the way, awesome work with this project, I can't wait to use it more <3

**Comment by pshihn** [comment]
Ah yes. This is a side effect of this optimization I did for SVG Paths. This does not happen in other drawing primitives. I guess I can give up some performance to do this the right way. 
Thanks for trying it out!

**Comment by ashiqur1986** [comment]
dongko

**Comment by ashiqur1986** [comment]
Ala casa le pagar

**Comment by pshihn** [comment]
Took me 2 years to fix this. 😅
Those rest of the code works with canvas transforms, SVG paths did not. 
Glad to say that it works in 4.2.0 
https://jsfiddle.net/kpa39Lst/2/
