### ISSUE TITLE
Complement documentation for import/require in 4.0

### ISSUE THREAD

**Issue by brunok** [pshihn/rough#130]
Please complement the documentation for importing/requiring roughjs. 

as says in [](https://roughjs.com/posts/release-4.0/) :

>  the location and names of the bundled resources have changed.

But I didn't find any mention of the correct way to do it in the documentation. People used to node_modules will probably check out that folder and find the correct import, others could be quite lost.

so, for  **CommonJS**:
`const rough = require( 'roughjs/bundled/rough.cjs.js');`

and for **ES Modules**:
`import rough from 'roughjs/bundled/rough.esm.js';`

Hope this helps

**Comment by literallysofia** [comment]
This saved me a lot of time! Thanks!

**Comment by pshihn** [comment]
Thanks. Based on the project.json file. It should automatically be picked up now:
```json
 "main": "bundled/rough.cjs.js",
  "module": "bin/rough.js",
  "types": "bin/rough.d.ts",
  "browser": "bundled/rough.js",
```

**Comment by pshihn** [comment]
Also updated the docs. Thanks for reporting
