### ISSUE TITLE
Filling a path is always done with non-zero fill-rule

### ISSUE THREAD

**Issue by ygra** [pshihn/rough#131]
Is there an option for even-odd? Otherwise paths with holes are pretty impossible to draw

**Comment by pshihn** [comment]
can you share an example? it should be even-odd already

**Comment by ygra** [comment]
https://jsfiddle.net/uL12bxdj/1/ Looks non-zero to me. Perhaps because it's two sub-paths where the latter forms the hole, instead of a single sub-path intersecting itself?

**Comment by ygra** [comment]
Using a different path (taken from the SVG spec), winding direction indeed makes a difference, indicating non-zero-ness:

fill-rule=evenodd
![image](https://user-images.githubusercontent.com/1692688/73616756-c2866080-4617-11ea-85df-2e86b50aff93.png)
![image](https://user-images.githubusercontent.com/1692688/73616760-c9ad6e80-4617-11ea-93ae-d26d389fda08.png)

fill-rule=nonzero
![image](https://user-images.githubusercontent.com/1692688/73616766-d4680380-4617-11ea-8197-3315d1f1c9c0.png)
![image](https://user-images.githubusercontent.com/1692688/73616768-daf67b00-4617-11ea-808e-b4de6f69adcc.png)

**Comment by pshihn** [comment]
Yes I do realize the difference. Should definitely fix this
Just for notes, few things to consider here: 
1) The SVG 'path' fill algorithm at the moment is different than that from other shapes.
2) Is it something that rough should set or should the called set it before drawing the shape - this depends on 1
3) Consider the implementation for Canvas Vs SVG

**Comment by pshihn** [comment]
I have developed a new algorithm for path filling. Hopefully implement it in the next couple of days.

**Comment by pshihn** [comment]
Independent of the new algorithm, fixed the evenodd issue in v4.1.3
https://jsfiddle.net/wytpsLr6/2/

**Comment by jesperkc** [comment]
This problem still exists when using https://unpkg.com/roughjs@4.3.1/bundled/rough.js

https://jsfiddle.net/rwpgx2t0/
