### ISSUE TITLE
zigzag fill style does not work properly on concave paths

### ISSUE THREAD

**Issue by ygra** [pshihn/rough#133]
![image](https://user-images.githubusercontent.com/1692688/73616677-c5cd1c80-4616-11ea-827c-55de22df3a13.png)

Drawn with `polygon`, but I guess `path` would do the same.

**Comment by pshihn** [comment]
Sadly, yes. It's a new algorithm that fails the zig-zag format. I will make it fall back to the old implementation till I tweak the algo for zig-zag

**Comment by pshihn** [comment]
btw, `path` will NOT do the same. It currently fills using traditional fill patterns

**Comment by pshihn** [comment]
I did a major upgrade fro SVG paths, sadly I  could not find a good solution for this fix yet. 
It's the next major item to resolve

**Comment by pshihn** [comment]
Fix in 4.2.1
