### ISSUE TITLE
When using Jest and import a non-bundled roughjs modules, Jest throws an error

### ISSUE THREAD

**Issue by GasimGasimzada** [pshihn/rough#136]
![Screen Shot 2020-02-05 at 12 25 19 PM](https://user-images.githubusercontent.com/807231/73824022-dd70f480-4812-11ea-8964-053cb17458d4.png)

My test file only has one line of code:

```
import { randomSeed } from "roughjs/bin/math";
```

I am not certain on what the issue is but it seems like it is related to how these packages are bundled.

Also, this error occurs when import anything from the bin directory:

```
import rough from 'roughjs/bin/rough';
```

For importing the main rough object, using bundled import fixes the issue:

```
import rough from 'roughjs';
```

However, the line above does not work when using webpack (e.g within Create React App).

**Comment by pshihn** [comment]
Everything in the bin folder is in ES6 module format
I'm assuming your react/jest bundling expects it to be in some other format?

**Comment by GasimGasimzada** [comment]
Yeah, maybe Jest doesn't use Babel (`babel-node` or something similar) to run the app. I will investigate to see if it is possible to do anything about it.

**Comment by GasimGasimzada** [comment]
@pshihn one question regarding this. Is it possible to get `import rough from 'roughjs';` this one working in a normal webpack + babel based application? Currently, importing like that gives the following error:

> TypeError: roughjs__WEBPACK_IMPORTED_MODULE_13___default.a.canvas is not a function. (In 'roughjs__WEBPACK_IMPORTED_MODULE_13___default.a.canvas(_this2.canvas)', 'roughjs__WEBPACK_IMPORTED_MODULE_13___default.a.canvas' is undefined)

**Comment by pshihn** [comment]
Seems like webpack issues. 

FWIW, roughjs does ship with a commonjs bundled version. Not sure how you;d include it : roughjs/bundled/rough.cjs.js

**Comment by GasimGasimzada** [comment]
It is solved. It can be closed now. Thank you for the help!
