### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by piepjaquet9** [pshihn/rough#137]
Hi,

There are quit a few broken links on:
https://github.com/pshihn/rough/wiki/Examples

The dist folder (mentioned on https://github.com/pshihn/rough) is also missing

**Comment by theonlygusti** [comment]
All of the images won't preview in the wiki https://github.com/pshihn/rough/wiki/Examples

**Comment by pshihn** [comment]
Links are fixed. There's a new "Gallery" page coming on the website which will have links to more. examples

**Comment by ggorlen** [comment]
Image links seem broken again throughout the wiki.
