### ISSUE TITLE
Issue with d3 example

### ISSUE THREAD

**Issue by jsonnull** [pshihn/rough#14]
When trying to view [the d3 example](http://roughjs.com/examples/bar-chart.html) I get a

```
ReferenceError: rough is not defined
```

**Comment by pshihn** [comment]
What browser/version are you using? Works on latest chrome/firefox

**Comment by vjeux** [comment]
Seems to also be working on mobile safari. This looks like the js file didn’t load, do you happen to use an adblocker by any chance? It may be blocking the js by mistake

**Comment by jsonnull** [comment]
This is on Firefox 58. I don't think it's blocker-related, as the request goes through in the network tab of developer tools with no errors. No failing requests, 200 response.

**Comment by jsonnull** [comment]
Looks like there's no `rough` variable defined, if you look at the script from jsdelivr it reads

```js
var RoughCanvas=function(){/* */}
```

**Comment by pshihn** [comment]
I believe the jsdeliver CDN is sending you the older version of the build. Maybe your CDN node has not updated its cache. 
I just changed the page to use an alternate source: https://cdn.rawgit.com/pshihn/rough/9be60b1e/dist/rough.min.js 
Try again.

**Comment by jsonnull** [comment]
Yeah, looks like that fixed it!
