### ISSUE TITLE
ellipse solid fill broken in 4.1.3

### ISSUE THREAD

**Issue by bynormous** [pshihn/rough#142]
Started using rough today with a simple ellipse with these options and couldn't get fill to work: 

```
{
	fill: 'red',
	fillStyle: 'solid',
	seed: 1
}
```

Downgrading to 4.1.0 magically fixed it so I'm assuming it's a bug.

**Comment by pshihn** [comment]
This was introduced in 4.1.3 and fixed in 4.1.4

**Comment by bynormous** [comment]
confirmed! thanks!
