### ISSUE TITLE
Holes in paths are filled

### ISSUE THREAD

**Issue by kevinzwang** [pshihn/rough#158]
Hello!

I'm drawing some paths with RoughJS that holes. For example: 
<img width="417" alt="image" src="https://user-images.githubusercontent.com/20215378/81365668-a1f9f680-909d-11ea-9d58-75eb4c43d9f8.png">

However, when I try to fill them, the holes are filled as well, in fact they're filled in twice, once by the outer path and once by the inner path.
<img width="425" alt="image" src="https://user-images.githubusercontent.com/20215378/81365762-e5ecfb80-909d-11ea-9c81-ff3488021a69.png">

I did some more digging and in [the examples page](https://github.com/pshihn/rough/wiki/Examples), the second example looks like it has a rectangle at the top left corner that has a hole that is correctly unfilled, but if you click on the links to view on Glitch, that rectangle is rendered with the same behavior I have been seeing myself, with a filled hole. This seems to indicate that this was a feature that worked before but has since broke. 

Would greatly appreciate a fix to this.

**Comment by pshihn** [comment]
Yes something changed recently. So now if your PATH is actually composed of multiple disconnect paths, like in your case, you need to set `combineNestedSvgPaths: true` in the options. 
I have updated the Glitch 

e.g.
```javascript
rc.path('M37,17v15H14V17z M50,5H5v50h45z', {
      stroke: 'red',
      strokeWidth: '1',
      fill: 'blue',
      combineNestedSvgPaths: true
});
```

**Comment by kevinzwang** [comment]
Awesome. thanks!
