### ISSUE TITLE
Sync API by default?

### ISSUE THREAD

**Issue by roman01la** [pshihn/rough#16]
Hello! Really great lib, thanks! I was wondering what's the motivation behind making draw API async by default? It makes it impossible to use synchronously, consider the following example

![dykqvbzw4aaojiy](https://user-images.githubusercontent.com/1355501/37337794-0a8451ec-26be-11e8-9e2a-ac3e857eb594.png)

While it's trivial to lift sync API into async world, it's impossible to go the other way around. I imaging having async proxy would make it backwards compatible. Also I understand that it probably meant to run in a web worker, but since it's still can be executed on the main thread it would be nice to provide an "easier" way of consuming the API. Thanks!

**Comment by pshihn** [comment]
Thanks for reporting this. It was my intention to make it work sync properly, just an oversight on my part. In the meantime you can use async/await to get around your issue.

```js
(async () => {
  await rc.circle(180, 220, 100, {
    fill: 'green', strokeWidth: 4, hachureGap: 8, fillWeight: 6
  });
  await rc.circle(250, 220, 120, {
    fill: 'red', strokeWidth: 4, hachureGap: 8, fillWeight: 6
  });
})();
```

**Comment by roman01la** [comment]
Awesome! I really like the simplicity of the library, looking forward for this change in master!

**Comment by pshihn** [comment]
Resolved with https://github.com/pshihn/rough/commit/185af6edc874fd810035d1ac635e51b09606c205
