### ISSUE TITLE
Failed to execute 'createPattern' on 'CanvasRenderingContext2D': The canvas width is 0

### ISSUE THREAD

**Issue by died** [pshihn/rough#19]
Hi, I modify the demo with D3 version 4 success.
https://died.github.io/us-map.html

But when I change topojson to other country, it give out a error 
> Uncaught (in promise) DOMException: Failed to execute 'createPattern' on 'CanvasRenderingContext2D': The canvas width is 0.
>     at t.path (https://cdn.jsdelivr.net/gh/pshihn/rough/dist/rough.min.js:1:24757)

I think it should be topojson content issue but it's my first time using topojson, so I have no idea to fix it,  any tips ? Thank.

topojson source
https://github.com/jason2506/Taiwan.TopoJSON/blob/master/topojson/counties.json 

code different with Taiwan topojson, other same as us-map.html
```
      d3.json("counties.json", async (error, tw) => {
        if (error) throw error;
        let topo = topojson.feature(tw, tw.objects.map).features;
        for (let feature of topo) {
          await rc.path(path(feature), {
            fill: randomColor(),
            fillStyle: randomStyle(),
            hachureAngle: randomAngle()
          });
        }
      });
```

**Comment by pshihn** [comment]
My initial guess is that one of the paths being generated has zero size, causing the hachure fill to fail. 
Which is probable something I should deal with in the code. 

Can you try setting the fill style to be 'solid' rather than random, and see if it works?
```js
await rc.path(path(feature), {
  fill: randomColor(),
  fillStyle: 'solid'
});
```

**Comment by died** [comment]
After setting the style to solid and remove angle fix the error message, thank you.

Now I need to figure out why this thing can't show normally as us-map.
https://died.github.io/tw-map.html
I know it's topojson content make it different, but no idea how to do, any tip ?

**Comment by pshihn** [comment]
I'll give it a try later today. I think there may be a bug in the library as well where it's not dealing with zero sized paths.

**Comment by died** [comment]
Thank you for the kindly help.

**Comment by died** [comment]
Hi @pshihn , I figured out that, the map need set the projection right or it can't display as expected.
Sorry I am new on D3.js so it take time to find it out.  Thank you for answer my stupid question.

https://died.github.io/tw-map.html 
The result with RoughJS was good.

**Comment by pshihn** [comment]
This is great. Sorry I wasn't much help.
