### ISSUE TITLE
Animation Capability

### ISSUE THREAD

**Issue by julianfrank** [pshihn/rough#20]
Any Plans to bring Animation capability like move, bounce, debounce etc?

**Comment by pshihn** [comment]
The goal is to provide native primitives so it can be used with any other library (for animation or otherwise)
Check out this: https://beta.observablehq.com/@jashkenas/tumble-wheel-with-rough-js
and https://beta.observablehq.com/@jashkenas/scratchy-eyes

**Comment by hpvd** [comment]
awesome examples !
