### ISSUE TITLE
rectangle not working correctly

### ISSUE THREAD

**Issue by julianfrank** [pshihn/rough#22]
rc.line(60, 300, 700, 60);
    rc.rectangle(60, 300, 700, 60, {
      fill: 'rgba(255,0,0,0.2)',
      fillStyle: 'solid',
      roughness: 2
    });
    rc.rectangle(60, 300, 700, 60, {
      fill: 'red',
      stroke: 'blue',
      hachureAngle: 60,
      hachureGap: 10,
      fillWeight: 5,
      strokeWidth: 5
    });

Line draws correctly but both rectangles draw with wrong co-ordinates

**Comment by pshihn** [comment]
I think it's working fine: https://jsfiddle.net/4L5ju643/5/
Note that the arguments to rectangle are (x, y, width, height)
[rectangle spec here](https://github.com/pshihn/rough/wiki#rectangle-x-y-width-height--options)
