### ISSUE TITLE
Does this library support react native?

### ISSUE THREAD

**Issue by dustturtle** [pshihn/rough#23]
I want this work for RN, so cool~

**Comment by pshihn** [comment]
Don't suppose so because it works on HTML Canvas only at the moment. 
I have plans to add native SVG rendering - maybe there's a way to integrate SVG into native.

**Comment by dustturtle** [comment]
Oh, thanks a lot! Really awesome work you have done!

**Comment by henrymoulton** [comment]
@pshihn I've been looking into using this for React Native using https://github.com/react-native-community/react-native-svg, is there anyway this could work?

**Comment by pshihn** [comment]
@henrymoulton It may not work directly, but could be adapted to work with it now that RoughJS supports SVG. The obvious way is to use generators to create PathInfo objects. These are just object that define how the shape is draw. Then you can use this path info to render using react-native-svg. https://github.com/pshihn/rough/wiki/RoughGenerator#svg-path-info
