### ISSUE TITLE
There seems to be a problem when rendering inside "requestAnimationFrame" on Firefox

### ISSUE THREAD

**Issue by 4lejandrito** [pshihn/rough#24]
[This](https://jsfiddle.net/k1g6533y/13/) works in Chrome and Firefox (uses setInterval).
[This](https://jsfiddle.net/65q7c5to/) only works in Chrome (uses requestAnimationFrame).

Any idea why?

Thanks!

**Comment by pshihn** [comment]
This is likely due to inherent async nature of RoughJs. Something that I overlooked because I wasn't thinking about animation. I have to see how much of surgery it needs to resolve this. Essentially I'd hate to have 2 different APIs - one from async stuff and slightly different for synch. *thinking* 
Related issue: https://github.com/pshihn/rough/issues/16

**Comment by pshihn** [comment]
The general idea of animation works thoough. See [this](https://beta.observablehq.com/@jashkenas/tumble-wheel-with-rough-js) and [this](https://beta.observablehq.com/@jashkenas/scratchy-eyes)

**Comment by 4lejandrito** [comment]
Hi @pshihn,

Glad to hear you already have this in mind. 

I was just playing with rough and wanted to let you know about the issue. Feel free to close it if you want. 

Thanks for such a great library :)

**Comment by AriaFallah** [comment]
Also running into this: https://www.aria.ai/snake.html doesn't render anything in firefox

**Comment by pshihn** [comment]
I've got a plan of attack  to resolve this. Stay tuned. I'll probably get some time tomorrow to work on this.

**Comment by pshihn** [comment]
This firefox bug is also causing this behavior https://bugzilla.mozilla.org/show_bug.cgi?id=1193394
There are two issues here. Fixing either one will make animations work again.
The firefox bug will be out in Firefox 60. 
Making Rough.js truly synchronous by default will also fix this - which I'm working on.

**Comment by pshihn** [comment]
Should be resolved with latest version (2.0.1). The same example with new build: https://jsfiddle.net/rho2k45t/2/

commit:
https://github.com/pshihn/rough/commit/185af6edc874fd810035d1ac635e51b09606c205
