### ISSUE TITLE
using in react?

### ISSUE THREAD

**Issue by bansal-rahul** [pshihn/rough#28]
How can I use this library in my react or react-native app?

**Comment by KeitIG** [comment]
You can probably use this library in combination of the `componentDidMount` library for first draw, and `componentWillUpdate` for subsequent redraws (if your drawings are dependent of your component props).

**Comment by pshihn** [comment]
I'm not a react guy, but someone posted a snippet on Twitter that you may find useful: https://twitter.com/LefiTarik/status/973360236764463105

**Comment by KeitIG** [comment]
I could try doing binding for React, should not be too hard. I'll see if I have time this week-end.

**Comment by KeitIG** [comment]
aaaand nevermind, it already exists https://www.npmjs.com/package/react-rough I think this can be closed.

**Comment by pshihn** [comment]
Actually that react imp is for the previous beta version of roughjs. I have since rewritten the code for a simpler API. Maybe you can update that particular package? or create a new one. Don't think that one would work with the new api.

**Comment by KeitIG** [comment]
Yep I can do that

**Comment by ooade** [comment]
Hi! I've bin busy but I quickly made an update.
### Installation
```sh
 npm install react-rough@next
```
### Usage
For now ReactRough takes `render` prop and gives you the rough canvas instance, so you could do whatever you wish with it.
> This API will not likely change so it's safe to use. I'd just add Rough Components (Circle, Arc, e.t.c), work on docs and make a full release.
```jsx
import ReactRough from 'react-rough'

render(<ReactRough
		width="500"
		height="200"
		render={rc => {
			rc.circle(80, 120, 50) // centerX, centerY, diameter
			rc.ellipse(300, 100, 150, 80) // centerX, centerY, width, height
			rc.line(80, 120, 300, 100) // x1, y1, x2, y2
		}}
	/>)
```

**Comment by pshihn** [comment]
@ooade My bad on changing the API on you.  It was early and no one was using it at the time. Sorry about that.
