### ISSUE TITLE
miscalculation of midDispY

### ISSUE THREAD

**Issue by nabesgo** [pshihn/rough#29]
Hi, very nice project! I love it !

I found a miscalculation at line 545 in renderer.js (also line 1190 in rough.js)
```
    let midDispX = o.bowing * o.maxRandomnessOffset * (y2 - y1) / 200;
    let midDispY = o.bowing * o.maxRandomnessOffset * (x1, x2) / 200;
```

I think It would be ...
```
    let midDispX = o.bowing * o.maxRandomnessOffset * (y2 - y1) / 200;
    let midDispY = o.bowing * o.maxRandomnessOffset * (x1 - x2) / 200;
```

Best regards

**Comment by pshihn** [comment]
Yes! Thank you.

**Comment by pshihn** [comment]
Resolved in https://github.com/pshihn/rough/commit/a047b23318715cd63bd584ae6fecec6effc10a65
