### ISSUE TITLE
Publish to npm?

### ISSUE THREAD

**Issue by ooade** [pshihn/rough#3]

**Comment by pshihn** [comment]
Will do. I wanted to sort some performance issue before I did that. 
But, since I'm not going to get around to doing that anytime, soon - I will upload the current version on npm and bower this weekend.

**Comment by c0bra** [comment]
@pshihn I guess this never happened?

**Comment by pshihn** [comment]
Ahhh. Sorry about this guys. I kinda abandoned this project for  a while. Back now. Working on a new release with WebWorkers -> much better performance. 
I will put this version on npm soon.

**Comment by pshihn** [comment]
published on npm 
'npm install --save roughjs'
https://www.npmjs.com/package/roughjs

'
