### ISSUE TITLE
`RoughSegmentRelation`

### ISSUE THREAD

**Issue by Niggler** [pshihn/rough#30]
[`segment.js` exports a function `RoughSegmentRelation`](https://github.com/pshihn/rough/blob/master/src/segment.js#L1) which merely returns an object:

```js
export function RoughSegmentRelation() {
  return {
    LEFT: 0,
    RIGHT: 1,
    INTERSECTS: 2,
    AHEAD: 3,
    BEHIND: 4,
    SEPARATE: 5,
    UNDEFINED: 6
  };
}
```

In every single place the value is used outside of the `segment.js` file, the function is called and a particular key is accessed.  For example, in [`renderer.js`](https://github.com/pshihn/rough/blob/master/src/renderer.js#L708):

```js
      if (s1.compare(s2) == RoughSegmentRelation().INTERSECTS) {
```

Questions:

1) is the import in [`canvas.js`](https://github.com/pshihn/rough/blob/master/src/canvas.js#L1) necessary?  It is not used in the body of `canvas.js`.

2) [`hachure.js`](https://github.com/pshihn/rough/blob/master/src/hachure.js#L54) calls the function twice and accesses the same key:

```js
        if (s.compare(this.sLeft) == RoughSegmentRelation().INTERSECTS) {
...
        if (s.compare(this.sRight) == RoughSegmentRelation().INTERSECTS) {
```

Shouldn't that value just be cached?  Ideally the entire thing would be cached, in the same way that `segment.js` caches the value in `RoughSegmentRelationConst`

3) every use of `RoughSegmentRelation` outside of `segment.js` follows the same pattern:

```js
if(segment1.compare(segment2) == RoughSegmentRelation().INTERSECTS)
```

`SEPARATE` and `UNDEFINED` are theoretically interesting distinctions, but that is not used outside of the implementation of `compare`.  Would it make more sense to convert that to an `intersects` method that just returned true if the two segments intersected?

**Comment by pshihn** [comment]
1: Yes it wasn't required. It's been fixed separately 
2,3: You're right about how RoughSegmentRelation is being used right now. The reason the code is structured so, is because there were other features in development that did not make it to release.  Those features used this function in other ways. 
Perhaps I should simplify the code till I get around to those features. It might reduce the build size a tad bit.
