### ISSUE TITLE
Fill is sometimes outside the polygon

### ISSUE THREAD

**Issue by mheden** [pshihn/rough#35]
If I define a polygon like this, the "filling" ends up outside the polygon: https://jsfiddle.net/mtytutua/
```
    rc.polygon([
      [100, 100], [300, 100], [300, 200], [200, 200],
      [200, 300], [300, 300], [300, 400], [100, 400], [100, 100]], {
      stroke: 'red',
      hachureAngle: 65,
      fill: 'rgba(0,0,255,0.6)'
    });
```
It looks like part of the "filling" is doubled. 

Great library BTW!

**Comment by pshihn** [comment]
This sometimes happens in .polygon() method when the shape is not a convex polygon. 
If you draw the same shape using SVG path, it renders fine. 
See: https://jsfiddle.net/5fjh2vvd/1/ as a workaround.

**Comment by pshihn** [comment]
In the meantime, using [path](https://github.com/pshihn/rough/wiki#path-d--options) may be an alternative to draw the shape.

**Comment by pshihn** [comment]
Resolved as part of https://github.com/pshihn/rough/pull/72
