### ISSUE TITLE
Basic chart examples

### ISSUE THREAD

**Issue by bumbeishvili** [pshihn/rough#40]
Tried to combine and put together rough.js and several basic charts

Hope this link land on your example page

https://beta.observablehq.com/@bumbeishvili/trying-out-rough

**Comment by pshihn** [comment]
Really nice. I will add this to the page. 
Btw, you can make the map look a bit more hand drawn by setting the simplification  (0.2-0.5 may be a good value for US map) https://github.com/pshihn/rough/wiki#simplification 
Of course, people may not want simplification.

**Comment by pshihn** [comment]
Added to https://github.com/pshihn/rough/wiki/Examples

**Comment by bumbeishvili** [comment]
@pshihn  
Nice catch, it looks better after simplifying  I think
