### ISSUE TITLE
Create SVG Renderer

### ISSUE THREAD

**Issue by pshihn** [pshihn/rough#41]
Similar to RoughCanvas, RoughSVG will create an svg node

```javascript
let rsvg = rough.svg(svgRoot, config);
let rect = rsvg.rectangle(10, 10, 100, 100);

// now can add custom styles to node
rect.classList.add('cool-rect');
svgRoot.appendChild(rect);
```

**Comment by ccjmne** [comment]
This is **great**, I can't wait!

SVG would mean the possibility for CSS styling, hovering animation, clicky-clicky stuff, easy fix for the guy who wants to implement a snake game without reshaping his snake's individual chunks...

The only downside is... I **actually** can't wait 😂

Anything I can do to help?

**Comment by pshihn** [comment]
I'm actually, almost done.
One thing left to do is the best way to fill an arbitrary path with hachure. Should I draw them as I do with defined shapes or should I use a pattern fill. Just playing with it till I find the best fit.

**Comment by ccjmne** [comment]
Sweet, thank you very much :)
This will make Rough immensely more practical for me (and a lot of others).

**Comment by pshihn** [comment]
SVG rendering is now part of Rough.js v.2.1 https://github.com/pshihn/rough/pull/49
See https://github.com/pshihn/rough/wiki for docs.
