### ISSUE TITLE
Default Property Values Incorrect in Documentation

### ISSUE THREAD

**Issue by MilesManners** [pshihn/rough#44]
In the [documentation](https://github.com/pshihn/rough/wiki), the default values for `fillWeight`, `hachureGap`, and `simplification` are incorrect.

`fillWeight` is listed as `strokeWidth`, but the default is `-1`
`hachureGap` is listed as `strokeWidth`, but the default is `-1`
`simplification` is listed as `1`, but the default is `0`

**Comment by pshihn** [comment]
You're right.  As it stands simplification 0 means no simplification. Setting it to 1 will actually simplify the curves a little bit. 

As for fillWeight, hachureGap - the value is dynamically calculated at render time. A value of -1 will cause the current value of strokeWidth to be used.

**Comment by MilesManners** [comment]
Thanks for clarifying. The reason I'm not still not 100% sure about `fillWeight` and `hachureGap` is because passing `1` for both of them and `strokeWidth` results in different behavior, but I'm doing some DPR scaling, so it may something unrelated to the defaults anyway.

**Comment by pshihn** [comment]
https://jsfiddle.net/9j64h2r1/6/ may help

fillWeight by default is 0.5 * strokeWidth
hachureGap by default is 4 * strokeWidth

if you set strokeWidth = 1, fillWeight =4, then you should update your hachureGap to be > 4 or it will be too tight.

**Comment by pshihn** [comment]
Just noticed a bug which you may be running into. {fillWidth: 4}, and {fillWidth: 4, strokeWidth: 1} should produce the same results. But it is not. In the later, the hachureGap needs to be set as well. That's definitely a bug. I'll fix that.

**Comment by MilesManners** [comment]
That one may not be a bug, in that fiddle, the rough canvas has a default `strokeWidth` so its being overridden in the drawing https://jsfiddle.net/he85xaua/4/

I think I just misread the initial values for `hachureGap` and `fillWeight` when I was first reading the docs.

**Comment by pshihn** [comment]
Documentation updated.
