### ISSUE TITLE
Seems bot to work on IE11 or Edge 

### ISSUE THREAD

**Issue by zoosky** [pshihn/rough#47]
* not

**Comment by AddictArts** [comment]
It can be fixed with mixed results, for example rc.path did not work, no Path2D support?
```
// I was able to add or install dev dependencies babel-cli, ... listed below and then the babel-polyfill
 "devDependencies":
    "babel-cli": "^6.26.0",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-es2017": "^6.24.1",
    "uglify-js": "^3.3.16"

  "dependencies":
    "babel-polyfill": "^6.26.0"
```
And you need a suitable babelrc
```
{
  "presets": [ "es2017", "es2015" ]
}
```

And then a way to run babel and uglify, for example I added to package.json
```
    "babel-es5": "babel dist/rough.js -o dist/rough.es5.js",
    "minify-u": "uglifyjs dist/rough.es5.js -o dist/rough.min.js",
```

**Comment by OSUblake** [comment]
> It can be fixed with mixed results, for example rc.path did not work, no Path2D support?

IE11 does not support Path2D. Edge does, but there is an issue with SVG path data.
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/8438884/

**Comment by pshihn** [comment]
Path2D is only used when filling with hachure styles in paths. Not in issue for other shape constructs. 
I want to move away from Path2D anyway because it will solve some other minor issues as well. Working on some good algorithms that may work as an alternative

**Comment by pshihn** [comment]
The build now includes an ES5 version.

**Comment by zoosky** [comment]
Cool

**Comment by Nalca** [comment]
I tried the ES5 version and it does not work on IE11. 
Not when the keyword **async** is present. It's a ES2017 keyword.

**Comment by pshihn** [comment]
@Nalca you're right 
I need to run this through babel to fix those. May need a Promise polyfill as well. 
PRs welcome. Not sure when I'll get a chance.

**Comment by AddictArts** [comment]
I used the babel-polyfill to fix the missing "async" after running into it. Simple add to my project build.

**Comment by pshihn** [comment]
Removed Path2D dependency.
