### ISSUE TITLE
algorithms

### ISSUE THREAD

**Issue by zhf459** [pshihn/rough#48]
Hi, great job!!! I'm very interested in the algorithm behind this, but a little hard to understand the code, will you give me some resource about the algorithm? thank you ^_^

**Comment by pshihn** [comment]
Yes, I have been meaning to write something up about this. Haven't had a chance yet. Maybe in a few days when I get some time.

**Comment by krishnaanaril** [comment]
@pshihn Do you have any update? :)

**Comment by frozar** [comment]
@pshihn Hi, maybe there is some news about this issue currently, no?

**Comment by pshihn** [comment]
2 years too late :)
https://shihn.ca/posts/2020/roughjs-algorithms/

**Comment by frozar** [comment]
@pshihn Whaou, I just see the date of your blog post, I just wrote it, amazing! I'm proud to have pushed you in this direction :wink:
