### ISSUE TITLE
Failed to minify rough.umd.js:19

### ISSUE THREAD

**Issue by emeeks** [pshihn/rough#53]
I'm getting this error when trying to build [Semiotic](https://github.com/emeeks/semiotic) using `roughjs 2.1.1`:

```
Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file: 

 	./node_modules/roughjs/dist/rough.umd.js:19 
```

**Comment by pshihn** [comment]
Closing this in favor of https://github.com/pshihn/rough/issues/54
I believe it is a es5 compatible build issue.
