### ISSUE TITLE
Issue appending svg element in js vs. using hardcoded svg element

### ISSUE THREAD

**Issue by lobenichou** [pshihn/rough#57]
Hey! This is possibly a noob question but here we go! 

I want to use this library to create custom html markers on a map. The issue is that the markers are generated in javascript and not hardcoded.  Basically, doing something like this doesn't work: 

```
const el = document.createElement('svg');
el.id = 'svg';
document.getElementsByTagName("BODY")[0].appendChild(el);

const svg = document.getElementById('svg')
const rc = rough.svg(svg)
svg.appendChild(rc.circle(80, 120, 50, {roughness: 2.8, fill: 'black'}))
svg.appendChild(rc.line(80, 120, 300, 100, {roughness: 2.8, fill: 'black'}))
```
The code: https://jsfiddle.net/szvoqhhf/

Am I missing something? I see the `g` and `path` element being appended properly. Should I be using https://github.com/pshihn/rough/wiki/RoughGenerator#svg-path-info?

**Comment by pshihn** [comment]
Couple of things.

* when creating a SVG node form javascript, you need to use `createElementNS` rather than `createElement`
* You already have the svg element as el. You don't need to do getElementById. `const svg = el;`

https://jsfiddle.net/1wz21p1k/2/

**Comment by pshihn** [comment]
Btw, your main problem is not providing the namespace. getElementById is just redundant code that would have worked anyway. SVG Nodes are in a different namespace than HTML

**Comment by lobenichou** [comment]
Well I learn something new. Thanks. It worked: 

<img width="570" alt="screen shot 2018-04-18 at 1 53 23 pm" src="https://user-images.githubusercontent.com/5431395/38957612-f0e7ea64-430f-11e8-94c5-03000671490d.png">
