### ISSUE TITLE
Add support for alternating hachure

### ISSUE THREAD

**Issue by sydeslyde** [pshihn/rough#58]
I would love to see an option for a zig-zag hachure fill pattern like in the [handy](https://www.gicentre.net/handy/using) processing library with `setIsAlternating(true)`.

I think it is a more realistic way of filling a shape when drawing quickly to zig-zag it instead of drawing countless paralell lines.

**Comment by pshihn** [comment]
Yes i've been meaning to add that and other fill styles. I have an implementation that works, but trying to improve the performance by trying some alternative algorithms. The default should probably, still be parallel hachures.

**Comment by sydeslyde** [comment]
Nice, so we could say that's coming some time :smile:
Is there a way to see your current implementation in action?

I'm fine with the defaults, I just though it could be nice to have the option.

**Comment by pshihn** [comment]
Some old code sitting in an older repository. I might have some time this weekend, I will post it publicly.

**Comment by ismay** [comment]
That sounds great. I think having the zigzagging fill style would be nice for simulating pencil drawings, something handy is very good at

**Comment by pshihn** [comment]
v2.2.1 has this and more:
https://github.com/pshihn/rough/releases/tag/v2.2.1
