### ISSUE TITLE
Add support for randomness-seed option

### ISSUE THREAD

**Issue by sydeslyde** [pshihn/rough#59]
I tried to create a little drawing application.
For this I collect shapes in an array which is repainted to a `canvas` when something changes or something new is created.
But this results in already drawn shapes to be re-rendered with new randomness each time, which causes these shapes to flicker, even when they are not changing.
(since there is no way to delete a shape, I have to reset the canvas to white every render)

For cases like this there could be an option to pass along to the render-methods to supply a custom seed for randomness for the roughness. Then it would render identically each time.
e. g. `roughCanvas.rectangle(10, 10, 200, 200, { randomSeed: 1234567 });`

[Visualzation of use case](https://codepen.io/anon/pen/mLJLwW?editors=1010)

Since `Math.random()` does not support seeding, a custom random number generator is needed.

If wanted, I'd happily implement this and supply a pull request if we can think of a suitable random number algorithm.

**Comment by pshihn** [comment]
Already supported. See discussion on https://github.com/pshihn/rough/issues/27 not be alternate seeding but by persisting shapes. This has advantages in some other use cases. 
Generators solve this: https://github.com/pshihn/rough/wiki/RoughGenerator

**Comment by sydeslyde** [comment]
I'm surprised that I missed that, thank you very much, works like a charm. :+1:
