### ISSUE TITLE
i made it to 8000 stars. 

### ISSUE THREAD

**Issue by wolfram77** [pshihn/rough#61]
this tool looks beautiful i hope someone makes a chart.js using it so i can then use it.
also some sketch font would be cool otherwise the chart could look wierd.

**Comment by pshihn** [comment]
Thanks

Not with chart.js, but this works well with D3. Here's an example: https://bl.ocks.org/aaizemberg/b403ba342cf0cd32d3e8a77174dcf8a0
and another example: https://beta.observablehq.com/@bumbeishvili/trying-out-rough

There are a bunch of hand drawn fonts out there that could be used. (including in the first exmaple). There's a request for that as well: https://github.com/pshihn/rough/issues/43
