### ISSUE TITLE
Adding transform attribute to svg rendering

### ISSUE THREAD

**Issue by gnhamity** [pshihn/rough#62]
Thanks for this, really great resource.

Wanting to use for my physics svg files which make use of transform attribute:
`    <path d="M 0,0 A 11.25 9 0 0 0 11.25,-9 A 3.75 6 0 1 0 3.75,-9 A 11.25 9 0 0 0 15,0 A 11.25 9 0 0 0 26.25,-9 A 3.75 6 0 1 0 18.75,-9 A 11.25 9 0 0 0 30,0 A 11.25 9 0 0 0 41.25,-9 A 3.75 6 0 1 0 33.75,-9 A 11.25 9 0 0 0 45,0 A 11.25 9 0 0 0 56.25,-9 A 3.75 6 0 1 0 48.75,-9 A 11.25 9 0 0 0 60,0" transform="translate(100,90) rotate(153.435)"></path>
`
Is there functionality available to do the translation/rotations, etc?

**Comment by pshihn** [comment]
If you're using Rough SVG, it is very easy. draw commands return a node and you can apply the transform attribute to the node

Here's an example: https://jsfiddle.net/8n2Lrqj2/

Hope that solves your problem
