### ISSUE TITLE
Incorrect rendering of SVG arcs

### ISSUE THREAD

**Issue by sydeslyde** [pshihn/rough#63]
It's me again. :grin:

I tried creating shapes with the `rc.path()` function using SVG-Paths.
But the arcs which are supposed to appear are not drawn correctly using the rough-canvas.
I tried fiddling with the comma-separators between values, relative `a` and absolute `A` instructions, none of them creates the right shape.
Drawing the shape directly to the danvas via a `Path2D` object works fine.

Interestingly enough, the fill for the shape is rendered correctly, just the outline is rendered wrong.
Also the four examples found on the website work perfectly in the same canvas.

I created a codepen to illustrate the issue -> [codepen](https://codepen.io/anon/pen/jxLZpR?editors=0010)

Am I missing something again or is this an actual bug?

**Comment by pshihn** [comment]
Seems like a bug. Let me take a look.

**Comment by pshihn** [comment]
v2.1.3 should have the fix for this.

**Comment by pshihn** [comment]
@sydeslyde  Adapted your codepen with the fix: https://codepen.io/shihn/pen/GdGoYQ
