### ISSUE TITLE
Hachure fill cutoff in SVG-Path polygons

### ISSUE THREAD

**Issue by sydeslyde** [pshihn/rough#65]
I found out the hachure fill in SVG-Path shapes is limited to the size of the canvas.
This means a shape larger than the canvas itself will be not filled completely.

See my [codepen for demonstration](https://codepen.io/anon/pen/OZwdKG?editors=0010)
(The startingpoint can be moved with the sliders, the other points are fixed to the edges. Moving the startingpoint to negative values results in the hachure fill being cut off at the bottom/right)

**Comment by pshihn** [comment]
I think this may be specific to Path rendering. Might work for polygons and other shapes. 

It may also be related to Canvas only. Have to try it in on SVG rendering as well to see if there's a common easy solution

**Comment by sydeslyde** [comment]
SVG rendering has a similar issue ([see this codepen](https://codepen.io/anon/pen/OZoqNd?editors=0010)), but its cut off only on way (either at the bottom or on the right).

Also as you assumed, the issue is related to path-rendering, since I could not repreduce it with `rc.polygon()` ([see here](https://codepen.io/anon/pen/zjmNgp?editors=0010)).
I just had to parse the slider-values to `int` before passing it to the array, or it wouldn't render the shape correctly.

**Comment by pshihn** [comment]
Fixed with https://github.com/pshihn/rough/pull/77
available in v2.2.3
