### ISSUE TITLE
Can I convert an existing svg to render with rough?

### ISSUE THREAD

**Issue by heaversm** [pshihn/rough#66]
I am using [two.js](https://github.com/jonobr1/two.js) to render out a hand-drawn path animation in svg, but I would love to give it a rough line texture that your library provides. Is this possible? What's the easiest way to accomplish this?

**Comment by pshihn** [comment]
Should be possible.
If you have the path's "d" attribute then you can pass it to rough.js
https://github.com/pshihn/rough/wiki#path-d--options

**Comment by pshihn** [comment]
Also, @ismay is working on a project that may be related: https://github.com/ismay/coarse

**Comment by ismay** [comment]
I’ve also just released https://github.com/ismay/coarse-cli, which allows you to do the conversion from the command line. There might be edge cases where it doesn’t work as expected, in that case feel free to let me know.

**Comment by marcusklaas** [comment]
your tool works beautifully @ismay - thanks for making and sharing it!!

**Comment by ismay** [comment]
Thanks, glad you like it! 👍
