### ISSUE TITLE
Allow for serverside rendering with jsdom

### ISSUE THREAD

**Issue by ismay** [pshihn/rough#67]
I'd like to use roughjs serverside with jsdom, but rough breaks when the global variable `self` isn't present. I saw that there are a couple of areas where `self` is used, surrounded by checks, but the checks themselves break because of a referenceerror.

I updated the checks to not throw an error when self doesn't exist in #68.

**Comment by ismay** [comment]
There's a lot of different ways to solve this of course, but for example, this a sketch of how the above could be addressed:

```javascript
const jsdom = require('jsdom');
const rough = require('roughjs');

// Create dom
const { JSDOM } = jsdom;
const dom = new JSDOM();
const document = dom.window.document;

// Pass window to rough
rough.init({
  window: dom.window
})

// Create svg
const svg = document.createElementNS("http://www.w3.org/2000/svg", "svg");
document.body.appendChild(svg);
const rc = rough.svg(svg);

// Draw shapes
const node = rc.rectangle(50, 50, 200, 200, { roughness: 2.8, fill: 'blue' });
svg.appendChild(node);

console.log(svg.outerHTML);
```

It depends on if you want to break the existing api, if it's important that rough instantiates as soon as possible, etc.

You could also add an extra option to the global config that allows you to pass in `window`. That seems like a nice way to keep backwards compatibility, at the cost of delaying execution until either `.svg` or `.canvas` is called:

```javascript
const jsdom = require('jsdom');
const rough = require('roughjs');

// Create dom
const { JSDOM } = jsdom;
const dom = new JSDOM();
const document = dom.window.document;

// Create svg
const svg = document.createElementNS("http://www.w3.org/2000/svg", "svg");
document.body.appendChild(svg);
const rc = rough.svg(svg, { window: dom.window });

// Draw shapes
const node = rc.rectangle(50, 50, 200, 200, { roughness: 2.8, fill: 'blue' });
svg.appendChild(node);

console.log(svg.outerHTML);
```

I think personally I'd prefer the latter.

**Comment by ismay** [comment]
Or even simpler, just update the bits of code that are using self to not throw an error when self doesn't exist 😋. Sorry for all the noise, was just thinking out loud. I'll send you a PR.

**Comment by pshihn** [comment]
Thanks for the fix. I'll take a look when I get a chance.  Been too swamped with other stuff :/

Btw, have you looked at https://github.com/pshihn/rough/wiki/RoughGenerator and using `toPaths` with it. Getting raw path information may be more useful than creating a virtual dom. Depending on the situation of course.

**Comment by ismay** [comment]
> I'll take a look when I get a chance. Been too swamped with other stuff :/

No problem, take your time, I'm not in a hurry 😊. As for the changes, I think the only real change is moving the self._roughScript assignment in `generator.js`. Maybe you want to do that differently, but it made sense to me since that's the only place it's used.

Other than that the changes preserve functionality, but prevent an error from being thrown, so they're just simple fixes.

> Btw, have you looked at https://github.com/pshihn/rough/wiki/RoughGenerator and using toPaths with it. Getting raw path information may be more useful than creating a virtual dom. Depending on the situation of course.

That sounds good, I'll take a look at that. Would be great to not have to create a virtual dom 👍

**Comment by pshihn** [comment]
I have ported the code from Javascript to TypeScript. In the process, I have also tried to address this issues. I have not actually tested it yet. Will updated this issue if fixed.

**Comment by ismay** [comment]
For it's been fixed with the new version 👍
