### ISSUE TITLE
fill overflow

### ISSUE THREAD

**Issue by NERVdy** [pshihn/rough#69]
```javascript
rc.polygon([[0, 0], [44, 0], [216/2, 185-75], [216-44, 0], [216, 0], [216/2, 185], [0, 0]], { fill: '#41b883', stroke: '#41b883' })
```
Is this a bug or normal?

**Comment by pshihn** [comment]
This is a known issue with  Concave Polygons: https://github.com/pshihn/rough/issues/35

You can work around it by using SVG Paths instead. Here's your shape as SVG path: https://jsfiddle.net/wso9c111/2/
