### ISSUE TITLE
SyntaxError: Unexpected use of reserved word 'let' in strict mode

### ISSUE THREAD

**Issue by alex374** [pshihn/rough#71]
SyntaxError: Unexpected use of reserved word 'let' in strict mode
In iOS 9.x, there are probloms with usage of 'let' or 'const'...

**Comment by pshihn** [comment]
You would have to create an es5  compatible build for that. 
Related: https://github.com/pshihn/rough/issues/54

**Comment by pshihn** [comment]
Now we have es5 builds which will solve this issue.
