### ISSUE TITLE
hachure vs hatching

### ISSUE THREAD

**Issue by zenril** [pshihn/rough#74]
Not a big issue but I think based on a google search alone
hachure is
**parallel lines used in hill-shading on maps, their closeness indicating steepness of gradient.**

hatching or cross hatching
**(in drawing or graphics) shade (an area) with intersecting sets of parallel lines.**

maybe hatching is better?

**Comment by pshihn** [comment]
Been using `hachure` for a while now, so it might not be backwards compatible to change. I might create an alias for `hatching`.  Already using `cross-hatch`.

Note there are different fill styles:
_ hachure_ creates parallel lines
_cross-hatch_  created intersecting lines 

https://github.com/pshihn/rough/wiki#fillstyle

**Comment by zenril** [comment]
Fair enough, I should have looked into it more, Sorry.

**Comment by pshihn** [comment]
No problemo.
