### ISSUE TITLE
TS compilation since Async feature

### ISSUE THREAD

**Issue by Ricard** [pshihn/rough#82]
Hello @pshihn, thank you for this great contribution 👯 👏 

Since version 2.2.0, which introduce async methods, I'm not being able to build the library inside angular 6 app.
I do not provide OS and versions information because the issue reside on types of `RoughCanvasAsync` (promise of...) not matching the implemented class `RoughCanvas`.

Here you could see an evidence [![Build Status](https://semaphoreci.com/api/v1/ricard/railingeditor/branches/roughjs-not-building/shields_badge.svg)](https://semaphoreci.com/ricard/railingeditor/branches/roughjs-not-building/builds/1)

**Comment by dispix** [comment]
I have issues with the typing too. I wanted to test the library in a react + typescript environment and got this behavior:

![image](https://user-images.githubusercontent.com/11643701/42634230-f03e6870-85e2-11e8-9f7d-5bf7c2d2572b.png)

![image](https://user-images.githubusercontent.com/11643701/42634277-0db0743e-85e3-11e8-92ef-28e147f10060.png)

**Comment by pshihn** [comment]
@Ricard  I have cleaned up the interfaces: https://github.com/pshihn/rough/pull/84 should fix this

**Comment by pshihn** [comment]
Available in v2.2.5

**Comment by dispix** [comment]
@pshihn you can see the configuration in the sandbox, there's nothing special there and it works for other libraries so I have no idea where it comes from. I thought this was related to this issue but if you want I can create a new one.

**Comment by pshihn** [comment]
@dispix  When I go to your url https://xoz411z0mq.codesandbox.io/ it loads fine and draws a box

Also, the error you're getting is that `canvas` is not defined in rough, where as type types clearly has the definition: https://github.com/pshihn/rough/blob/master/bin/rough.d.ts 

My theory is that in the sandbox environment, either typings file is not being picked up, or when you import, it is importing the wrong type of module. There's a UMD version in the dist folder and there's the es6 module in the bin folder.

**Comment by pshihn** [comment]
It seems like codesandbox.io is not paying attention to the `types` property in `package.json`.

**Comment by pshihn** [comment]
Alright.. A couple of things:
Since module being loading typescript is not the commonjs module,  https://www.typescriptlang.org/docs/handbook/modules.html says that import should be like this:
```typescript
import rough from 'roughjs';
```
But it doesn't work properly on codesandbox. 

Here's the working example based on your code that works on stackblitz:
https://stackblitz.com/edit/react-ts-mofibf

Hope this helps, @dispix
