### ISSUE TITLE
Imported rough object doesn't exist when running tests in JSDom

### ISSUE THREAD

**Issue by DylanSp** [pshihn/rough#85]
I experienced an odd error when trying to test an app using this library. The app's written in Typescript, using React, using Jest and Enzyme for testing. I have a component that imports this library with
`import rough from "roughjs";`
then tries to use it to draw with this code:
```
const rc = rough.canvas(this.canvasRef.
rc.line(100, 0, 100, 300);
```
However, when running tests using `react-scripts-ts --env=jsdom`, this code error's out with `Error: Uncaught [TypeError: Cannot read property 'canvas' of undefined`. This happens even if canvas or canvas-prebuilt is installed in the project. I can fix the problem by checking `if (rough)` before drawing, which would seem to indicate that the `rough` object doesn't exist in the test environment.

**Comment by pshihn** [comment]
Sorry for not getting back to you sooner. This seems like an issue with the environment setup by `react-scripts-ts`
I don't see an issue with using rough in plain TS code. Will look into it. 
If you have a codesandbox/jsbin like example, it would be a great help to start

**Comment by pshihn** [comment]
Look at https://excalidraw.com/ how they're using this in React.
