### ISSUE TITLE
Implement dashed lines

### ISSUE THREAD

**Issue by rodinhart** [pshihn/rough#86]
This would be a great addition I think.

**Comment by pshihn** [comment]
Are you thinking for stroke or for filling a shape?

**Comment by rodinhart** [comment]
Just the stroke.

**Comment by pshihn** [comment]
It will be interesting to add that to the hachure fill as well. 
Of course it is possible to do that already by mucking with the context of the canvas or setting the attributes of the SVG element.

Here's an example with Canvas:
https://jsfiddle.net/shihn/khegrxt3/

```javascript
const canvas = document.querySelector('canvas');
const ctx = canvas.getContext('2d');
const rc = rough.canvas(canvas);

ctx.setLineDash([5]);
rc.rectangle(10, 10, 150, 150);
rc.rectangle(10, 180, 150, 150, {fill: 'red'});
```

**Comment by akira-cn** [comment]
My [PR](https://github.com/pshihn/rough/pull/88) added to both canvas and SVG stroke.

**Comment by rodinhart** [comment]
Thanks for the suggestion of "mucking" with the canvas context; this will definitely serve my use-case.

To be picky, the result does not look very much like how one would sketch dashed lines: the dashes are too far apart and not lined up:

![image](https://user-images.githubusercontent.com/8900626/50277635-d9321e00-043c-11e9-8f56-113659295a62.png)

Still, a solution in some cases (including mine).

Thanks.

**Comment by pshihn** [comment]
Yes, I agree this needs an alternative solution for better rendering. 
Part of the rough algorithm is overlaying multiple lines with randomness. Just adding a dash offset will not be the best solution. 
You may find playing with dash lengths may create favorable results - still a lot of randomness of https://jsfiddle.net/shihn/wfzLdqbh/

I will keep this issue open till a built in solution is implemented. I have some thoughts on that but probably won't get to it till the new year.

**Comment by rodinhart** [comment]
Excellent, thanks.

**Comment by rodinhart** [comment]
Usage example, just to illustrate:

![image](https://user-images.githubusercontent.com/8900626/50283419-bfe59d80-044d-11e9-8f5f-bbb02a878c82.png)

**Comment by pshihn** [comment]
@rodinhart This looks neat! Mind sharing your project name? I am compiling a list of projects using rough.js

**Comment by rodinhart** [comment]
It's used to render the statechart used as the state controller in OrgVue. No link to project code I'm afraid, it's closed source.
https://orgvue.com/

**Comment by akira-cn** [comment]
@pshihn Using rough.js and dagre.js draw hand-writing style flowchart. The project is https://github.com/spritejs/sprite-extend-dagre .

**Comment by pshihn** [comment]
BTW proper dashed line support has landed in master: https://github.com/pshihn/rough/pull/159 will be in the next release
