### ISSUE TITLE
option to not stroke?

### ISSUE THREAD

**Issue by jedierikb** [pshihn/rough#90]
Can prevent a polygon stroke by setting `stroke: 'transparent'`.
Maybe setting to null can avoid unnecessary paint calls?

**Comment by pshihn** [comment]
Yes, it's a feature I've been meaning to add. As it stands, setting stroke to `transparent` is the only way to do it.

**Comment by pshihn** [comment]
Now supported in https://github.com/pshihn/rough/pull/121
Use `stroke: "none"` in the options.
