### ISSUE TITLE
TS - toPaths expects "Drawable", generator shapes are created as "Drawable | Promise<Drawable>"

### ISSUE THREAD

**Issue by AndrewBerry** [pshihn/rough#93]
This might come down to my lack of TS knowledge.

I'm trying to grab the SVG paths of a circle created by a generator with the following code:

```js
import Rough from "roughjs";
const generator = Rough.generator({ async: false }, { width: 200, height: 200 });
const shape = generator.circle(10, 10, 10);
const paths = generator.toPaths(shape); // error here
```
The error being reported:
```
Argument of type 'Drawable | Promise<Drawable>' is not assignable to parameter of type 'Drawable'.
  Type 'Promise<Drawable>' is missing the following properties from type 'Drawable': shape, options, sets
```

`shape` is of type `Drawable | Promise<Drawable>` but the argument of `generator.toPaths()` is expecting to be of type `Drawable`.

Is there a fix that I can do on my end? Or, should I change the type of the `toPaths()` argument to `Drawable | Promise<Drawable>` and submit a PR?

**Comment by pshihn** [comment]
Yes.  This interface is not as clean as I'd like it to be. It will be cleaner when async/sync ops are separated out. 

You can easily get around it by telling TS the generator is not async. You know that because you set `async: false`. So your code will look like:

```javascript
const generator = rough.generator({ async: false }, { width: 200, height: 200 }) as RoughGenerator;
const shape = generator.circle(10, 10, 10);
const paths = generator.toPaths(shape); // error here
```

**Comment by AndrewBerry** [comment]
Ah - I didn't know about the `as` keyword. Cheers!

**Comment by pshihn** [comment]
v3.0 (released today) has cleaner separation of Async/Sync versions now. Closing this.
