### ISSUE TITLE
Add changelog  

### ISSUE THREAD

**Issue by ismay** [pshihn/rough#96]
I was wondering what has changed from major version 2 to 3, and couldn't find a changelog.md. Is there another place where I can see what's changed?

If not, it'd be nice to add a changelog (or something similar) to the project.

**Comment by pshihn** [comment]
Uhmm yeah. My bad. 
I will add one. 

To answer your question. the only thing that changed was a major refactor. No API change
The main purpose of this was to separate sync/async versions of the build. 
So now there's rough.js and rough-async.js as build outputs.

**Comment by pshihn** [comment]
Changelog added and up to date with latest
