### ISSUE TITLE
How to use rough with other canvas library

### ISSUE THREAD

**Issue by lyyourc** [pshihn/rough#97]
I wanna add drag and drop on canvas items via [konvajs](https://konvajs.github.io) 👻

Seems that `rough.generator` is not capable 😣

**Comment by pshihn** [comment]
Not sure how konvajs works but I have seen people use roughjs with other libs like physics engines for games. You can use the same canvas between the libs.

**Comment by lyyourc** [comment]
Could you provide an simple example T T

**Comment by pshihn** [comment]
I'm not sure I want to figure out konvajs. If you supply an example that does not work for you, I can take a look
